### PR TITLE
Parser for annotated data dictionary

### PR DESCRIPTION
**Pull request by l-k-**
Parses the site comments and implementation status out of an annotated data dictionary excel spreadsheet.

### CODE REVIEW

**Comment by bruth** [comment]
I ran it on the data dictionary you forwarded me and got an empty result:

``` json
{
    "Demographics": {},
    "Diagnosis": {},
    "Encounter": {},
    "Enrollment": {},
    "Procedure": {},
    "Vital": {}
}
```

I did get a warning from OpenPyXL itself:

``` python
/usr/local/lib/python3.4/site-packages/openpyxl/workbook/names/named_range.py:121: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")
```

Also, please include a README with a description and how to install, a requirements.txt with a list of dependencies, and a sample workbook with a test.

**Comment by l-k-** [comment]
Sorry about that. Added a test and instructions. 

The warning is there because the excel file has printer settings in it, and they are encoded using names like this:

```
<definedName name="_xlnm.Print_Area" localSheetId="2">'Data Description'!$A:$Q</definedName>
```

openpyxl doesn't know what to do with them, so it discards them. It can only process  names that refer to cell ranges. And it discards the rest, which are all the names that start with _xlnm. They are usually printer settings, and indeed that's what they are in the case of our test file.

**Comment by bruth** [comment]
Thanks. Here are a few minor changes:
- Lowercase table and field names
- Include the field even if the site comments or implementation status are empty
- Break parsing on the first empty field name

``` diff
diff --git a/services/data-dictionary/parser.py b/services/data-dictionary/parser.py
index f4e5161..dbabe2d 100755
--- a/services/data-dictionary/parser.py
+++ b/services/data-dictionary/parser.py
@@ -23,25 +23,31 @@ class Parser():
             worksheet = wb[name]

             # saw a space in the middle of one of the names. Get rid of those
-            name = name.replace(' ', '')
+            name = name.replace(' ', '').lower()

             if (not worksheet['D2'].value or
                     not worksheet['D2'].value.startswith('Site Comments')):
                 continue

             row_iter = worksheet.iter_rows()
+
+            # Skipping header rows.
             next(row_iter)
             next(row_iter)

             self.dictionary[name] = {}

             for row in row_iter:
-                if row[3].value or row[4].value:
-                    field = row[0].value.replace(' ', '')
-                    self.dictionary[name][field] = {
-                        'site_comments': row[3].value,
-                        'implementation_status': row[4].value,
-                    }
+                # Read until the first empty field name.
+                if row[0].value is None:
+                    break
+
+                field = row[0].value.replace(' ', '').lower()
+
+                self.dictionary[name][field] = {
+                    'site_comments': row[3].value or '',
+                    'implementation_status': row[4].value or '',
+                }

         self.parsed = True
```

**Comment by bruth** [comment]
> - Include the field even if the site comments or implementation status are empty

This is why I was getting an empty result back because there was not any data filled out.

**Comment by l-k-** [comment]
Thanks!

**Comment by bruth** [comment]
Looks good. It is ready to be squashed with a good commit message.

**Comment by l-k-** [comment]
Done. Thanks for the review!

**Pull request merged**
