### PR TITLE
Implement program to generate DQA template files

### LINKED ISSUE #9: Implement script to generate DQA template files
See PEDSnet/Data-Quality#75 for the full discussion. To provide a consistent starting point:

> I need a script that does the following: 
> Input: Model, Model Version, Data Version, Table 
> Output: secondary reports for all tables (with the first seven fields populated) in the correct directory within the DataQuality folder based on the provided data version

### PR DESCRIPTION
**Pull request by bruth**
Fix #9

Signed-off-by: Byron Ruth b@devel.io

### CODE REVIEW

**Comment by writetoritu** [comment]
Thanks for the scripts. I was able to generate the template using those scripts. Some comments (and request for minor changes to the script): 
- Could you change the order of goals to the following : Fidelity, Consistency, Accuracy, and Feasibility (also a typo there)?
- we don't need to generate the templates for the following tables: concept, concept_ancestor, concept_class, concept_relationship, concept_synonym, domain, and vocabulary 
-  can we also specify the version of the CDM in the command line? (e.g. v1 or v2 and so on)? (and also populate the model and data-version columns accordingly)
- one update to the format of the data-version column: Please also include the site name, e.g. PEDSnet-v2-CHOP-ETLv3

**Comment by bruth** [comment]
Thanks for reviewing it. I will make the changes. For the CDM, it defaults to the latest version of PEDSnet, but you can change that using the `--model` and `--version` options.

**Comment by writetoritu** [comment]
Thanks.
- I missed the table "source_to_concept_map" in the list of no-template tables 
- Can I specify the model version on command line (using the dqa-files command that you shared on hipchat) or do we need to modify the script?

**Comment by bruth** [comment]
> I missed the table "source_to_concept_map" in the list of no-template tables

I will add the table.

> Can I specify the model version on command line (using the dqa-files command that you shared on hipchat) or do we need to modify the script?

Yes you can do `dqa-files CHOP ETLv3 --version=v1`

**Comment by bruth** [comment]
@writetoritu Updated to exclude `source_to_concept_map` and updating the help text to correctly show the usage and added a README.

**Comment by bruth** [comment]
@writetoritu Once you confirm this is ready to go feel free to merge.

**Pull request merged**
