### PR TITLE
Create a service for PCORnet annotated data dictionary

### PR DESCRIPTION
**Pull request by l-k-**
based on the etl conventions service

### CODE REVIEW

**Comment by bruth** [comment]
Thanks for putting this together. Is GitHub where the annotated data dictionary is going to be stored?

**Comment by l-k-** [comment]
Yep, Kevin confirmed that it will be on github. And I'm looking at your changes for #26 now.

**Comment by bruth** [comment]
> Kevin confirmed that it will be on github.

Great, that makes things easier. Let's pick a location so the paths can be updated and the [token check](https://github.com/PEDSnet/pedsnet-origins/pull/27/files#diff-47c1279b78d0d3d881b6f3d696065bc4R162) can be uncommented or removed depending on the visibility of the repo.

Also, I opened #28 to apply after this PR is merged. It will abstract out the components in #26 so we can apply them here.

@murphyke @aaron0browne Please pick a repository and path for the annotated data dictionary.

**Comment by gracecodes144** [comment]
Somewhere in Data_Coordinating_Center, I'd think. We can create a new directory at the root called pcornet_add to store these files.

**Comment by gracecodes144** [comment]
Just noticed @murphyke's comment [here](https://github.com/PEDSnet/Data_Coordinating_Center/pull/126) which suggests /output/pcornet/annotated_data_dictionary. Let's go with that.

**Comment by bruth** [comment]
@l-k- The path of the file is `output/pcornet/annotated_data_dictionary.xlsx` in the `Data_Coordinating_Center` repo per https://github.com/PEDSnet/Data_Coordinating_Center/pull/129

**Comment by bruth** [comment]
Looks good, squash the commits and then merge.

**Pull request merged**
